### ISSUE TITLE
Difference in default values and README example values

### ISSUE THREAD

**Issue by jonas-klesen** [zyxxmu/DSnoT#1]
The default argument values in main.py are starkly different from the ones [in the README](https://github.com/zyxxmu/DSnoT#usage).

Which values should be used here in general, or does it vary widely per model and one has to tune them?

Thanks!
Jonas

**Comment by Lirui-Zhao** [comment]
Hi Jonas,

Thank you for bringing this to our attention. We appreciate your interest in our work. The inconsistency you've noticed between the default argument values in main.py and those in the README was an oversight on our part. We have now updated main.py to align with the examples provided in the README.

Please note that while these default values are a good starting point for general situations, custom adjustments might achieve better performance for the specific model you're using and your particular use case. If you have any further questions or run into issues while tuning these parameters, feel free to reach out.

Best regards,
Lirui Zhao
