### ISSUE TITLE
sparse model

### ISSUE THREAD

**Issue by kevinintel** [zyxxmu/DSnoT#2]
Hi,
I am interesting in your work.
Can you share 30% sparse llama2-7b?
I want to measure more metrics.

Thanks

**Comment by Lirui-Zhao** [comment]
Hi,

Thank you for your interest in our work and for reaching out with your request.

To obtain the 30% sparse version of the Llama2-7b model, you can modify and save the model using the command provided in our README.sh. Below is the specific command tailored to your needs:

```
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py \
    --model meta-llama/Llama-2-7b-hf \
    --prune_method DSnoT \
    --initial_method wanda \
    --sparsity_ratio 0.3 \
    --sparsity_type unstructured \
    --max_cycle_time 50 \
    --update_threshold 0.1 \
    --pow_of_var_regrowing 1 \
    --save_model
```

If you encounter any issues or have further questions about the process, please don't hesitate to reach out.

Best regards,
Lirui Zhao

**Comment by kevinintel** [comment]
Thanks, Lirui Zhao
