### ISSUE TITLE
WrappedGPT object has no attribute 'H'

### ISSUE THREAD

**Issue by jonas-klesen** [zyxxmu/DSnoT#3]
When running DSNOT with SparseGPT on an OPT model, i get the error above from the following line:

https://github.com/zyxxmu/DSnoT/blob/297993fd03b51875b3a2c605c9660e44cb67e37c/lib/prune_opt.py#L127

It seems like in the WrappedGPT, the H attribute is never set.

Looking at the code, this error probably also happens when running non-opt models, although i haven't tried.

**Comment by Lirui-Zhao** [comment]
Hi Jonas,

Thank you for pointing out this bug, we have updated [layerwrapper.py](https://github.com/zyxxmu/DSnoT/blob/main/lib/layerwrapper.py) to fix this.

Lirui Zhao

**Comment by jonas-klesen** [comment]
Thanks for the quick fix!
