### ISSUE TITLE
How to evaluate the zero-shot performance?

### ISSUE THREAD

**Issue by EugeneLiu01** [zyxxmu/DSnoT#4]
Hi, thanks for your inspiring and brilliant work!

I notice that there is no code for the evaluation of zero-shot performance. I was wondering whether this part of code is the same as [wanda](https://github.com/locuslab/wanda/blob/8e8fc87b4a2f9955baa7e76e64d5fce7fa8724a6/lib/eval.py#L132) ?

**Comment by Lirui-Zhao** [comment]
Thanks for your interest in our work. We use the original EleutherAI LM eval harness framework https://github.com/EleutherAI/lm-evaluation-harness.git. After the completion of our work, Wanda updated its zero-shot code which was modified utilizing the same framework. Although theoretical compatibility is anticipated, we have not tested this part of wanda's code.

**Comment by EugeneLiu01** [comment]
Thank you for your reply! I tried to zero-shot code from wanda, and it seems works well. But i met another problem.

Im trying to prune `opt-1.3b` with `sparsity_ratio=0.7` by `wanda` and `dsnot`, the cmd param is shown below.
```
# cmd params of wanda
    --prune_method wanda \
    --sparsity_ratio 0.7 \
    --sparsity_type unstructured \
    
# cmd params of dsnot
    --prune_method DSnoT \
    --initial_method wanda \
    --sparsity_ratio 0.7 \
    --sparsity_type unstructured \
    --max_cycle_time 50 \
    --update_threshold 0.1 \
    --pow_of_var_regrowing 1 
```
Perplexity is tested on wikitext2, by default. `wanda`'s result is 99.47, which is reasonable. However, `dsnot`'s result is 248.42.
The result is really confusing. I was wondering why it would be like this. Are there any other parameters that need to be specifically specified?
Thanks!~

**Comment by Lirui-Zhao** [comment]
Sorry for late reply. The primary focus of DSnoT is on LLMs that with more than 7B parameters. The performance of DSnoT may be lower than Wanda, specifically on the opt-1.3b with 70% sparsity rate.

**Comment by EugeneLiu01** [comment]
Thanks! I will try on more LLMs. And what do you think is the cause of this phenomenon?

**Comment by zyxxmu** [comment]
Hi, I'm happy to share some of my opinions here. I believe that optimizing layerwise reconstruction error (here in DSnoT) may not necessarily be suitable for small-scale models like 2.7B. Traditional knowledge in network sparsity tells us that fine-tuning such small sparse networks with a global sparsity objective may yield better results.

**Comment by EugeneLiu01** [comment]
> Hi, I'm happy to share some of my opinions here. I believe that optimizing layerwise reconstruction error (here in DSnoT) may not necessarily be suitable for small-scale models like 2.7B. Traditional knowledge in network sparsity tells us that fine-tuning such small sparse networks with a global sparsity objective may yield better results.

That's a valuable insight! and I'd better experiment and try more. Thanks for your help!
